import type { HeroProps } from "./schema";

// Captions follow CAPSULES.md #1; UI strings are the app's own (frontend/src/i18n/locales).

export const heroFr: HeroProps = {
  lang: "fr",
  shoot: "Tournage · 5 sept",
  files: "{n} fichiers",
  title: "Une heure de rushes.",
  silences: "Silences retirés.",
  hesitations: "Les hésitations aussi.",
  localBadge: "IA en local · rien n’est envoyé",
  exportCaption: "Votre timeline, prête.",
  editorCaption: "Chaque coupe reste éditable, dans votre logiciel.",
  appTitle: "Tournage du 5 sept",
  appSubtitle: "{status} · {n} fichiers · {from} → {to}",
  statusDone: "Terminée",
  cuts: "{n} coupes",
  wholeFile: "Fichier entier · {d}",
  endToEnd: "{n} fichiers bout à bout",
  preview: "Preview",
  exportVerb: "Exporter la timeline",
  menuTitle: "Timeline pour",
  segmentsTitle: "Ou un clip par coupe",
  nudge: "+{n} images",
  statsCaption: "Une heure de rushes, 40 minutes à monter.",
  statShorter: "Plus court",
  statSaved: "Montage économisé",
  statCuts: "Coupes",
  name: "AutoTrim",
  version: "2",
  tagline: "Coupe les silences. Et les euh.",
  multicamNote: "Aussi en multicam",
  hesitationLines: [],
  soundtrack: "",
  captions: [],
};

export const heroEn: HeroProps = {
  lang: "en",
  shoot: "Shoot · Sep 5",
  files: "{n} files",
  title: "An hour of footage.",
  silences: "Silences removed.",
  hesitations: "Hesitations too.",
  localBadge: "Local AI · nothing uploaded",
  exportCaption: "Your timeline, ready.",
  editorCaption: "Every cut still yours, in your editor.",
  appTitle: "Shoot · Sep 5",
  appSubtitle: "{status} · {n} files · {from} → {to}",
  statusDone: "Done",
  cuts: "{n} cuts",
  wholeFile: "Whole file · {d}",
  endToEnd: "{n} files end to end",
  preview: "Preview",
  exportVerb: "Export timeline",
  menuTitle: "Timeline for",
  segmentsTitle: "Or one clip per cut",
  nudge: "+{n} frames",
  statsCaption: "An hour of footage, 40 minutes to edit.",
  statShorter: "Shorter",
  statSaved: "Editing saved",
  statCuts: "Cuts",
  name: "AutoTrim",
  version: "2",
  tagline: "Cuts the silences. And the ums.",
  multicamNote: "Multicam too",
  // The session is in French: the English cut shows English lines over the same real waveform
  hesitationLines: ["sixteen euros [um…] the rounding", "and why [um…] my big brother", "but [um…] there you go."],
  soundtrack: "",
  captions: [],
};
